### ISSUE TITLE
Alice is not a constructor

### ISSUE THREAD

**Issue by artemnovichkov** [fletcherist/yandex-dialogs-sdk#101]
I'm a newbie in JS :) I tried to run:
```bash
nodemon index.js
```
and has an error:
```bash
const alice = new Alice()
              ^

TypeError: Alice is not a constructor
    at Object.<anonymous> (/Users/artemnovichkov/Documents/Projects/guess-numbers/index.js:2:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
Here is my index.js:
```js
const Alice = require('yandex-dialogs-sdk')
const alice = new Alice()

const random = (min, max) => Math.floor(Math.random * (max - min + 1)) + min

const { button } = Alice
alice.welcome(ctx => {
    ctx.reply({
        text: 'Привет! Я загадала число от 1 до 100. Сможешь отгадать его?',
        buttons: [button('Давай попробуем!', button('Нет'))]
    })
})

alice.command('Давай попробуем', ctx => {
    ctx.state.guessedNumber = random(1, 100)
    ctx.reply('Ну попробуй!')
})

alice.command('Нет', ctx => {
    ctx.reply('Спасибо за игру!')
})

alice.command(/^\d+$/, ctx => {
    const number = Number(ctx.message)
    if (number > ctx.state.guessedNumber) {
        ctx.reply('Мое число меньше чем ${number}')
    } else if (number < ctx.state.guessedNumber) {
        ctx.reply('Мое число больше чем ${number}')
    } else {
        ctx.reply({
            text: 'Ты победил! Я загадала число ${ctx.state.guessedNumber}',
            buttons: [button('Сыграть еще раз', button('Нет'))]
        })
    }
})

alice.any(ctx => {
    ctx.reply('Ты ввел не число. Поробуй еще раз')
})

const port = 3000
alice.listen('/', port, callback => console.log(port))
```

**Comment by fletcherist** [comment]
Hello, Artem!

You're trying to use an old version of sdk **(<2.0)**. If you want to use that outdated syntax, you should better switch on previous major version ( 1+ )

Here's an actual api to solve your problem:
```ts
const { Alice, Scene, Reply, Markup } = require('yandex-dialogs-sdk');

const alice = new Alice();

const random = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const M = Markup;

const welcomeMatcher = ctx => ctx.data.session.new === true;
alice.command(welcomeMatcher, ctx =>
  Reply.text('Привет! Я загадала число от 1 до 100. Сможешь отгадать его?', {
    buttons: [M.button('Давай попробуем!'), M.button('Не хочу')],
  }),
);

const startGame = ctx => {
  ctx.session.set('guessedNumber', random(1, 100));
  return Reply.text('Ну попробуй!');
};
alice.command('давай попробуем', startGame);
alice.command('сыграть ещё раз', startGame);
alice.command('Не хочу', ctx => Reply.text('Спасибо за игру!'));

alice.command(/^\d+$/, ctx => {
  const number = Number(ctx.message);
  const guessedNumber = ctx.session.get('guessedNumber');
  if (number > guessedNumber) {
    return Reply.text(`Моё число меньше, чем ${number}`);
  } else if (number < guessedNumber) {
    return Reply.text(`Моё число больше, чем ${number}`);
  } else {
    return Reply.text(
      `Ты победил! Я загадала число ${guessedNumber}. Сыграешь ещё раз?`,
      {
        buttons: [M.button('Сыграть ещё раз!'), M.button('Не хочу')],
      },
    );
  }
});
alice.any(ctx => Reply.text('Ты ввёл вообще не число. Попробуй ещё раз!'));

const server = alice.listen(8080, '/');
```

You can find more information at [README](https://github.com/fletcherist/yandex-dialogs-sdk/blob/master/README.md)

Thanks for the issue

**Comment by artemnovichkov** [comment]
Thanks, @fletcherist!
