### ISSUE TITLE
TypeError: Cannot read property 'session' of undefined

### ISSUE THREAD

**Issue by vitalets** [fletcherist/yandex-dialogs-sdk#111]
code:
```js
const { Alice, Reply } = require('yandex-dialogs-sdk');

const alice = new Alice();

alice.use((ctx, next) => {
  return next();
});

alice.any(ctx => {
  return Reply.text('Hello');
});

alice.listen(3000, '/');
```
output:
```js
(node:80625) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'session' of undefined
    at .../node_modules/yandex-dialogs-sdk/dist/stage/stage.js:32:26
    at next (.../node_modules/yandex-dialogs-sdk/dist/alice.js:48:20)
    at alice.use (.../src/index.js:6:10)
    at next (.../node_modules/yandex-dialogs-sdk/dist/alice.js:48:20)
    at .../node_modules/yandex-dialogs-sdk/dist/session/userSessionMiddleware.js:15:23
```

**Comment by vitalets** [comment]
@Yavanosta thanks!
Should be fixed [in docs](https://github.com/fletcherist/yandex-dialogs-sdk#middlewares).
